# Flattening

In [16]:
import numpy as np

In [9]:
a = np.array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]])

In [10]:
print(a)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [11]:
b=a.ravel()
print(b)

[0 1 2 3 4 5 6 7 8 9]


In [14]:
a.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [15]:
a.T.ravel()

array([0, 5, 1, 6, 2, 7, 3, 8, 4, 9])

# Reshaping

In [21]:
print(b)
b.reshape((2,5))
a.T.ravel().reshape(2,5)

[0 1 2 3 4 5 6 7 8 9]


array([[0, 5, 1, 6, 2],
       [7, 3, 8, 4, 9]])

In [49]:
a=np.array([0,1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
a.reshape(2,int(len(a)/2))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [33]:
a.reshape(2,-1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [51]:
print(a.shape)
b = np.array([[0, 1, 2, 3], [5, 6, 7, 8], [2, 6, 4, 1]])
print(b.shape)
c=a.reshape(5,2)
temp=a.copy()
d=temp.reshape(5,2)
#print(c)
d=b.reshape(6,2)
#print(d)

(10,)
(3, 4)


In [52]:
a[1]=-11
print(a)
print(c)
print(d)

[  0 -11   2   3   4   5   6   7   8   9]
[[  0 -11]
 [  2   3]
 [  4   5]
 [  6   7]
 [  8   9]]
[[0 1]
 [2 3]
 [5 6]
 [7 8]
 [2 6]
 [4 1]]


In [60]:
a=np.array([[0,1, 2, 3, 4], [5, 6, 7, 8, 9]])
b=a.reshape(2,5)
c=a.T.reshape(2,5)
a[1]=12
print(a)
print(b)
print(c)

[[ 0  1  2  3  4]
 [12 12 12 12 12]]
[[ 0  1  2  3  4]
 [12 12 12 12 12]]
[[0 5 1 6 2]
 [7 3 8 4 9]]


# Change Dimension

## Add Dimension

In [68]:
a=np.array([[0,1, 2, 3, 4,1], [5, 6, 7, 8, 9,3]])

print(a)
a.shape

[[0 1 2 3 4 1]
 [5 6 7 8 9 3]]


(2, 6)

In [74]:
b=a[:, np.newaxis]
print(b.shape)
c=a[:,:, np.newaxis]
print(c.shape)
d=a[np.newaxis,:,:]
print(d.shape)

(2, 1, 6)
(2, 6, 1)
(1, 2, 6)


## Dimension Shuffling


In [78]:
a = np.arange(24)
print(a)
a = np.arange(4*3*2).reshape(4, 3, 2)
print(a)
a = np.arange(4*3*2).reshape(4, 6)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [80]:
a = np.arange(4*3*2).reshape(4, 3, 2)
a.shape

(4, 3, 2)

In [81]:
a[0, 2, 1]

5

In [84]:
b = a.transpose(1, 2, 0)
b

array([[[ 0,  6, 12, 18],
        [ 1,  7, 13, 19]],

       [[ 2,  8, 14, 20],
        [ 3,  9, 15, 21]],

       [[ 4, 10, 16, 22],
        [ 5, 11, 17, 23]]])

In [85]:
# This will create a view not deepcopy
print(a[0, 2, 1])
b[2, 1, 0] = -1
print(a[0, 2, 1])

5
-1


# Resizing

In [96]:
a=np.array([0,1, 2, 3, 4, 5, 6, 7, 8, 9])
print(a)
print(a.size)
print(a.shape)

[0 1 2 3 4 5 6 7 8 9]
10
(10,)


In [97]:
a.resize((6,))
print(a)
a.resize((12,))
print(a)

[0 1 2 3 4 5]
[0 1 2 3 4 5 0 0 0 0 0 0]


In [99]:
a=np.array([0,1, 2, 3, 4, 5, 6, 7, 8, 9])
b = a
a.resize((4,)) 

ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False

# Sorting Data

In [112]:
a=np.array([9,0,1, 2, 3, 4, 5, 6, 7, 8])
b=np.sort(a)
print(a)
print(b)

[9 0 1 2 3 4 5 6 7 8]
[0 1 2 3 4 5 6 7 8 9]


In [115]:
a=np.array([[2,0,1, 3, 4], [9,5, 6, 7, 8]])
b=np.sort(a)
print(a)
print(b)

[[2 0 1 3 4]
 [9 5 6 7 8]]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [123]:
a=np.array([[2,0,1, 3, 4], [9,5, 6, 7, 8]])
b=np.sort(a,axis=0)
print(a)
print(b)
a.sort(axis=1)
a

[[2 0 1 3 4]
 [9 5 6 7 8]]
[[2 0 1 3 4]
 [9 5 6 7 8]]


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [127]:
# Sorting with fancy indexing:
a = np.array([4, 3, 1, 2])
j=np.argsort(a)
print(j)
a[j]

array([1, 2, 3, 4])

# Finding minima and maxima:

In [131]:
a = np.array([7,8,9,4,3,1,2])
i_max = np.argmax(a)
max_v = np.max(a)
print(i_max)
#print(max_v)
i_min = np.argmin(a)
min_v = np.min(a)
#print(i_min)
#print(min_v)

2


In [137]:
a=np.array([[2,0,1, 3, 4], [9,5, 6, 7, 8]])
i_max = np.argmax(a)
max_v = np.max(a)
print(i_max)
print(max_v)
i_min = np.argmin(a)
min_v = np.min(a)
#print(i_min)
#print(min_v)

5
9


# Comparisons

In [142]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])
c = np.array([4, 2, 2, 4])
a==b


array([False,  True, False,  True])

In [143]:
np.array_equal(a,b)

False

In [144]:
np.array_equal(b,c)

True

In [148]:
print(np.logical_and(a,b))
print(np.logical_or(a,b))
print(np.logical_xor(a,b))

[ True  True  True  True]
[ True  True  True  True]
[False False False False]


# Computing sums

In [150]:
a = np.array([1, 2, 3, 4])
np.sum(a)
a.sum()

10

In [155]:
a=np.array([[2,0,1, 3, 4], [9,5, 6, 7, 8]])
print(np.sum(a))
print(np.sum(a,axis=0))
print(np.sum(a,axis=1))

45
[11  5  7 10 12]
[10 35]


In [158]:
print(a)
a[:, 0].sum(), a[:, 1].sum(),a[:, 2].sum(), a[:, 3].sum(),a[:, 4].sum()

[[2 0 1 3 4]
 [9 5 6 7 8]]


(11, 5, 7, 10, 12)

# Broadcasting

In [186]:
a = np.arange(0, 40, 10)
a

array([ 0, 10, 20, 30])

In [187]:
a = np.tile(np.arange(0, 40, 10),(4,1))
a 

array([[ 0, 10, 20, 30],
       [ 0, 10, 20, 30],
       [ 0, 10, 20, 30],
       [ 0, 10, 20, 30]])

In [188]:
a = np.tile(np.arange(0, 40, 10),(4,1)).T
a

array([[ 0,  0,  0,  0],
       [10, 10, 10, 10],
       [20, 20, 20, 20],
       [30, 30, 30, 30]])

In [189]:
b = np.array([0, 1, 2,4])
print(a)
print(b)
a+b

[[ 0  0  0  0]
 [10 10 10 10]
 [20 20 20 20]
 [30 30 30 30]]
[0 1 2 4]


array([[ 0,  1,  2,  4],
       [10, 11, 12, 14],
       [20, 21, 22, 24],
       [30, 31, 32, 34]])

In [168]:
a = np.ones((4, 5))
a[1]=-3
a

array([[ 1.,  1.,  1.,  1.,  1.],
       [-3., -3., -3., -3., -3.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [170]:
a = np.ones((4, 5))
a[:,1]=-3
a

array([[ 1., -3.,  1.,  1.,  1.],
       [ 1., -3.,  1.,  1.,  1.],
       [ 1., -3.,  1.,  1.,  1.],
       [ 1., -3.,  1.,  1.,  1.]])

In [190]:
a = np.arange(0, 40, 10)
a.shape

(4,)

In [191]:
a = a[:, np.newaxis]
print(a.shape)
a

(4, 1)


array([[ 0],
       [10],
       [20],
       [30]])

In [193]:
b = np.array([0, 1, 2])
print(a)
print(b)

[[ 0]
 [10]
 [20]
 [30]]
[0 1 2]


In [194]:
a+b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])